//------------------------------------------------------------------------------
// <auto-generated>
    //     This code was generated by a tool.
    //     Runtime Version:4.0.30319.18046
    //
    //     Changes to this file may cause incorrect behavior and will be lost if
    //     the code is regenerated.
    //
//  </auto-generated>
  //------------------------------------------------------------------------------

namespace Resources {
  using System;


      /// <summary>
     ///   A strongly-typed resource class, for looking up localized strings, etc.
    ///
    ///</summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
  
      private static global::System.Resources.ResourceManager resourceMan;
  
      private static global::System.Globalization.CultureInfo resourceCulture;
  
      [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
      internal AppResources() {
        }
  
        /// <summary>
      ///   Returns the cached ResourceManager instance used by this class.
      ///
    /// </summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    public static global::System.Resources.ResourceManager ResourceManager {
    get {
    if (object.ReferenceEquals(resourceMan, null)) {
    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RadarcOnline.App.Presentation.Mvc.Resources.AppResources", typeof(AppResources).Assembly);
      resourceMan = temp;
      }
      return resourceMan;
      }
      }
  
      /// <summary>
      ///   Overrides the current thread's CurrentUICulture property for all
      ///   resource lookups using this strongly typed resource class.
      ///
    ///</summary>
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    public static global::System.Globalization.CultureInfo Culture {
    get {
    return resourceCulture;
    }
    set {
    resourceCulture = value;
    }
    }
        /// <summary>
      ///   Looks up a localized string similar to Continent.
     ///</summary>
      public static string MainPageViewModel_Continent 
      {
        get 
        {
          return ResourceManager.GetString("MainPageViewModel_Continent", resourceCulture);
        }
      }
      /// <summary>
      ///   Looks up a localized string similar to Title.
     ///</summary>
      public static string MainPageViewModel_Name 
      {
        get 
        {
          return ResourceManager.GetString("MainPageViewModel_Name", resourceCulture);
        }
      }
      /// <summary>
      ///   Looks up a localized string similar to Instructions.
     ///</summary>
      public static string MainPageViewModel_Instructions 
      {
        get 
        {
          return ResourceManager.GetString("MainPageViewModel_Instructions", resourceCulture);
        }
      }
      /// <summary>
      ///   Looks up a localized string similar to Ingredients.
     ///</summary>
      public static string MainPageViewModel_Ingredients 
      {
        get 
        {
          return ResourceManager.GetString("MainPageViewModel_Ingredients", resourceCulture);
        }
      }
      /// <summary>
      ///   Looks up a localized string similar to Image.
     ///</summary>
      public static string MainPageViewModel_Image 
      {
        get 
        {
          return ResourceManager.GetString("MainPageViewModel_Image", resourceCulture);
        }
      }
      /// <summary>
      ///   Looks up a localized string similar to Vegan.
     ///</summary>
      public static string MainPageViewModel_Vegan 
      {
        get 
        {
          return ResourceManager.GetString("MainPageViewModel_Vegan", resourceCulture);
        }
      }
      /// <summary>
      ///   Looks up a localized string similar to KCal.
     ///</summary>
      public static string MainPageViewModel_Calories 
      {
        get 
        {
          return ResourceManager.GetString("MainPageViewModel_Calories", resourceCulture);
        }
      }
      /// <summary>
      ///   Looks up a localized string similar to Prep. Time (min).
     ///</summary>
      public static string MainPageViewModel_PreparationTime 
      {
        get 
        {
          return ResourceManager.GetString("MainPageViewModel_PreparationTime", resourceCulture);
        }
      }
      /// <summary>
      ///   Looks up a localized string similar to Id.
     ///</summary>
      public static string MainPageViewModel_Id 
      {
        get 
        {
          return ResourceManager.GetString("MainPageViewModel_Id", resourceCulture);
        }
      }
      /// <summary>
      ///   Looks up a localized string similar to Recipies Ref Model.
     ///</summary>
      public static string AppName 
      {
        get 
        {
          return ResourceManager.GetString("AppName", resourceCulture);
        }
      }
      /// <summary>
      ///   Looks up a localized string similar to logo.png.
     ///</summary>
      public static string LogoImage 
      {
        get 
        {
          return ResourceManager.GetString("LogoImage", resourceCulture);
        }
      }
      /// <summary>
      ///   Looks up a localized string similar to 40.
     ///</summary>
      public static string LogoWidth 
      {
        get 
        {
          return ResourceManager.GetString("LogoWidth", resourceCulture);
        }
      }
      /// <summary>
      ///   Looks up a localized string similar to 40.
     ///</summary>
      public static string LogoHeight 
      {
        get 
        {
          return ResourceManager.GetString("LogoHeight", resourceCulture);
        }
      }
      /// <summary>
      ///   Looks up a localized string similar to logo.
     ///</summary>
      public static string LogoAlt 
      {
        get 
        {
          return ResourceManager.GetString("LogoAlt", resourceCulture);
        }
      }
      /// <summary>
      ///   Looks up a localized string similar to Main page.
     ///</summary>
      public static string MainPage 
      {
        get 
        {
          return ResourceManager.GetString("MainPage", resourceCulture);
        }
      }
      /// <summary>
      ///   Looks up a localized string similar to MainMenu.
     ///</summary>
      public static string MainMenu 
      {
        get 
        {
          return ResourceManager.GetString("MainMenu", resourceCulture);
        }
      }
      /// <summary>
      ///   Looks up a localized string similar to Main page.
     ///</summary>
      public static string MainMenu_MainPage1 
      {
        get 
        {
          return ResourceManager.GetString("MainMenu_MainPage1", resourceCulture);
        }
      }
  }
  }
